### PR TITLE
Extend Swift/Transport for Mandrill

### PR DESCRIPTION
**Pull request by nickurt**
Extend the SwiftTransport with a new Mandrill/driver, rather than overwriting the TransportManager completely ..

### CODE REVIEW

**Comment by therobfonz** [comment]
This is a good idea. Will pull down to test and merge if it checks out. Thanks for the tweak!

**Comment by therobfonz** [comment]
Ran a test and this unfortunately doesn't work. 'swift.transport' is not added to the container unless The MailServiceProvider is extended and parent::register() is called.

If you can adjust the service provider and do that, it should work.

**Comment by nickurt** [comment]
That's odd, I just pulled my branch in a new Laravel 6 application and everything is working as expected

composer.json
```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/nickurt/laravel-mandrill-driver"
    }
],

"require": {
    "therobfonz/laravel-mandrill-driver": "dev-patch-1"
},
```

.env
```
MAIL_DRIVER=mandrill
```

config\services.php
```php
'mandrill' => [
    'secret' => 'blablabla',
]
```
routes\web.php
```php
Route::get('/', function() {
    \Mail::raw('blablabla', function($mail) {
        //
    });
});
```

**Comment by therobfonz** [comment]
Interesting. It’s possible I missed something. When I have a solid chunk of time to review it, I’ll double check

**Comment by nickurt** [comment]
If you manually changed the files, you could have seen an error about the `mailer`, but a 

```
composer dump-autoload
```
will fix that ..

**Comment by therobfonz** [comment]
That was it...thanks. Merged and tagged.

**Pull request merged**
